tunnel: YOUR_TUNNEL_ID
credentials-file: C:\Users\YOUR_USER\.cloudflared\YOUR_TUNNEL_ID.json

ingress:
  - hostname: db.datac.click
    service: http://localhost:13000
  - hostname: pgadmin.example.com
    service: http://localhost:5050
  - service: http_status:404
